### ISSUE TITLE
Workshop January 2015

### ISSUE THREAD

**Issue by nathany** [edmontongo/presentations#8]
Saturday, January 24th

William Kennedy is coming to give our workshop!

## Todo list
- [x] Find a whiteboard at startup Edmonton
- [x] Find room capacity with tables (40! Oh wow.)
- [x] Workshop page on edmontongo.org
- [x] EventBrite event
- [x] Review the learning materials (Nathan)
- [x] Review the learning materials (Matthias)
- [ ] Plan following meetup to dovetail with workshop
- [x] Promotions and marketing
* [x] We need some raffle tickets for door prizes.  @nathany
* [x] Name tags of some sort (stickers and sharpies?) @nathany

## Details
* Lunch provided
* 8 hours of training and hands-on
* Starts at 9, we'll be there at 8:30 if people need help getting their development environment setup

**Comment by nathany** [comment]
* [ ] We need some raffle tickets for door prizes.
